# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: HireXpertUI      # it is the name of the workflow that will be displayed in the GitHub Actions tab
# This is a GitHub Actions workflow file that defines a CI/CD pipeline for a Node.js project.

on:
  push:                  # This is the section that defines the events that trigger the workflow  
    branches: [ "main" ] # Trigger on pull request to main branch
  pull_request:          # Trigger on push  to main branch
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
